### ISSUE TITLE
value error

### ISSUE THREAD

**Issue by k0st1an** [pynotifyme/notifymetools#1]
```
Traceback (most recent call last):
  File "/opt/notifymetools/env/bin/nm-tools.py", line 39, in <module>
    main()
  File "/opt/notifymetools/env/bin/nm-tools.py", line 26, in main
    notify.lost_film()
  File "/opt/notifymetools/env/lib/python3.4/site-packages/notifymetools/notification.py", line 61, in lost_film
    if telegram.lost_film(**data):
  File "/opt/notifymetools/env/lib/python3.4/site-packages/notifymetools/notification.py", line 32, in lost_film
    err_result = json.loads(err.result.text)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by k0st1an** [comment]
Всему виной символ в токене при отправку сообщения `POST /bot%E2%80%8B<token>`. Через `print()` символ не отображается. Легко отловить если использовать `len()`, должно быть 45, а не 46. Проблема кроется на стороне сайта, был криво записан в базу токен.
